version: '3.8'
services:
  app:
    build:
      context: .
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    image: homework-merge
    container_name: homework-merge
    command: 'gunicorn --bind 0.0.0.0:8000 app:application --reload'
    ports:
      - '80:8000'
    volumes:
      - '.:/app'
