version: '3.4'
services:
  app:
    build: .
    container_name: homework-merge
    command: 'gunicorn --bind 0.0.0.0:8000 app:application --reload'
    ports:
      - '80:8000'
    volumes:
      - '.:/app'
