app_name = flask_app
build:
	docker build -t flask_app .
run:
	docker run -p 80:8000 -v $(pwd):/app flask_app
kill:
	@echo 'Killing container...'
	@docker ps | grep $(app_name) | awk '{print $$1}' | xargs docker stop
